#!/bin/sh

while read local_ref local_sha remote_ref remote_sha
do
        if [ "$remote_ref" = "refs/heads/master" ]
        then
                pelican content -o output -s publishconf.py
                ghp-import -m "Update with latest content" output
                git push --no-verify origin gh-pages
        fi
done

exit 0